// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart": {
            "get": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Get the shopping cart for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get cart",
                "responses": {
                    "200": {
                        "description": "Cart retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.ShoppingCart"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Remove all items from the shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Clear cart",
                "responses": {
                    "200": {
                        "description": "Cart cleared successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/items": {
            "post": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Add a product item (SKU) to the shopping cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add item to cart",
                "parameters": [
                    {
                        "description": "Add Item Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AddItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item added successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/items/{product_item_id}": {
            "put": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Update the quantity of an item in the cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Update item quantity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product Item ID (SKU)",
                        "name": "product_item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Item Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item updated successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Remove an item from the shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Remove item from cart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product Item ID (SKU)",
                        "name": "product_item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item removed successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/items/{product_item_id}/selection": {
            "patch": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Set the selection state (selected/deselected) for a cart item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Set item selection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product Item ID (SKU)",
                        "name": "product_item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Selection Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SelectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item selection updated successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/items/{product_item_id}/toggle": {
            "post": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Toggle the selection state of a cart item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Toggle item selection",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product Item ID (SKU)",
                        "name": "product_item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item selection toggled successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/selected": {
            "delete": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Remove only items that are marked selected (used after checkout)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Clear selected items",
                "responses": {
                    "200": {
                        "description": "Selected items cleared successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/selection": {
            "patch": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Set selection state for all items in the cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Set selection for all items",
                "parameters": [
                    {
                        "description": "Select All Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SelectAllRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selection updated successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/shops/{shop_id}/selection": {
            "patch": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Set selection state for all items from a shop",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Set selection for shop items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shop ID",
                        "name": "shop_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Select Shop Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SelectShopRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selection updated successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/validate": {
            "post": {
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "description": "Validate selected items in the cart (ensure stock and availability) before checkout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Validate cart",
                "responses": {
                    "200": {
                        "description": "Cart is valid",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Cart invalid",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "Get list of orders for a user or session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "List orders",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Orders retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create shop_order(s) from the shopping cart. If cart contains items from multiple shops, creates multiple shop_orders (1 per shop).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Create order(s) from cart (Marketplace - Multi-shop)",
                "parameters": [
                    {
                        "description": "Order creation request",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order(s) created successfully (can be multiple shop_orders)",
                        "schema": {
                            "$ref": "#/definitions/service.CreateOrderResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/number/{order_number}": {
            "get": {
                "description": "Get order details by order number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get order by order number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Number",
                        "name": "order_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "description": "Get order details by order ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get order by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CartItem": {
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string"
                },
                "is_selected": {
                    "type": "boolean"
                },
                "price": {
                    "type": "number"
                },
                "product_item_id": {
                    "description": "✅ STORED in Redis",
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "shop_id": {
                    "description": "❌ NOT stored in Redis - Fetched from Product Service on-demand",
                    "type": "integer"
                },
                "sku_code": {
                    "type": "string"
                }
            }
        },
        "domain.Order": {
            "type": "object",
            "properties": {
                "earning_amount": {
                    "type": "number"
                },
                "final_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "description": "Relations",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.OrderItem"
                    }
                },
                "merchandise_subtotal": {
                    "description": "Financial snapshot (SOURCE OF TRUTH)",
                    "type": "number"
                },
                "order_number": {
                    "description": "Business identifiers",
                    "type": "string"
                },
                "ordered_at": {
                    "description": "Time",
                    "type": "string"
                },
                "payment_method": {
                    "description": "Payment",
                    "type": "string"
                },
                "platform_fee": {
                    "type": "number"
                },
                "shipping_address_id": {
                    "description": "Shipping",
                    "type": "integer"
                },
                "shipping_discount": {
                    "type": "number"
                },
                "shipping_fee": {
                    "type": "number"
                },
                "shop_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "Status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.OrderStatus"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "Ownership",
                    "type": "integer"
                },
                "voucher_discount": {
                    "type": "number"
                }
            }
        },
        "domain.OrderItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "price_at_purchase": {
                    "type": "number"
                },
                "product_item_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.OrderStatus": {
            "type": "string",
            "enum": [
                "pending",
                "paid",
                "processing",
                "shipped",
                "delivered",
                "cancelled"
            ],
            "x-enum-comments": {
                "OrderStatusCancelled": "Order has been cancelled",
                "OrderStatusDelivered": "Order has been delivered",
                "OrderStatusPaid": "Payment completed",
                "OrderStatusPending": "Order created, waiting for payment",
                "OrderStatusProcessing": "Order is being processed",
                "OrderStatusShipped": "Order has been shipped"
            },
            "x-enum-descriptions": [
                "Order created, waiting for payment",
                "Payment completed",
                "Order is being processed",
                "Order has been shipped",
                "Order has been delivered",
                "Order has been cancelled"
            ],
            "x-enum-varnames": [
                "OrderStatusPending",
                "OrderStatusPaid",
                "OrderStatusProcessing",
                "OrderStatusShipped",
                "OrderStatusDelivered",
                "OrderStatusCancelled"
            ]
        },
        "domain.ShoppingCart": {
            "type": "object",
            "properties": {
                "item_count": {
                    "description": "✅ COMPUTED FIELDS - Cart Service responsibility ONLY\nThese are DISPLAY metrics for Cart UI/Badge, NOT checkout logic",
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CartItem"
                    }
                },
                "selected_item_count": {
                    "description": "Selected items (rows)",
                    "type": "integer"
                },
                "selected_quantity": {
                    "description": "Sum of selected quantities",
                    "type": "integer"
                },
                "selected_total_price": {
                    "description": "Total price (selected)",
                    "type": "number"
                },
                "total_price": {
                    "description": "Total price (all)",
                    "type": "number"
                },
                "total_quantity": {
                    "description": "Sum of all quantities",
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "handler.AddItemRequest": {
            "type": "object",
            "required": [
                "quantity"
            ],
            "properties": {
                "product_item_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "description of the error"
                }
            }
        },
        "handler.SelectAllRequest": {
            "type": "object",
            "required": [
                "selected"
            ],
            "properties": {
                "selected": {
                    "type": "boolean"
                }
            }
        },
        "handler.SelectShopRequest": {
            "type": "object",
            "required": [
                "selected"
            ],
            "properties": {
                "selected": {
                    "type": "boolean"
                }
            }
        },
        "handler.SelectionRequest": {
            "type": "object",
            "required": [
                "selected"
            ],
            "properties": {
                "selected": {
                    "type": "boolean"
                }
            }
        },
        "handler.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation completed successfully"
                }
            }
        },
        "handler.UpdateItemRequest": {
            "type": "object",
            "required": [
                "quantity"
            ],
            "properties": {
                "quantity": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "service.CreateOrderRequest": {
            "type": "object",
            "required": [
                "shipping_address",
                "shipping_city",
                "shipping_name",
                "shipping_phone"
            ],
            "properties": {
                "payment_method": {
                    "type": "string"
                },
                "session_id": {
                    "description": "Deprecated",
                    "type": "string"
                },
                "shipping_address": {
                    "type": "string"
                },
                "shipping_address_id": {
                    "description": "THÊM MỚI - Reference address table",
                    "type": "integer"
                },
                "shipping_city": {
                    "type": "string"
                },
                "shipping_country": {
                    "type": "string"
                },
                "shipping_discount": {
                    "description": "Mã freeship",
                    "type": "number"
                },
                "shipping_fee": {
                    "description": "Financial (theo db-diagram.db)",
                    "type": "number"
                },
                "shipping_name": {
                    "description": "Shipping information",
                    "type": "string"
                },
                "shipping_phone": {
                    "type": "string"
                },
                "shipping_postal_code": {
                    "type": "string"
                },
                "shipping_province": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "voucher_discount": {
                    "description": "Mã giảm giá",
                    "type": "number"
                }
            }
        },
        "service.CreateOrderResponse": {
            "type": "object",
            "properties": {
                "order_numbers": {
                    "description": "Order numbers for each shop_order",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "orders": {
                    "description": "Multiple shop_orders (1 per shop)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Order"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "UserAuth": {
            "type": "apiKey",
            "name": "X-User-Id",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Order Service API",
	Description:      "Order Service API for e-commerce platform - Cart and Order management endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
