// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart": {
            "get": {
                "description": "Get the shopping cart for the current user or session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (if authenticated)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID (if guest)",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cart retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove all items from the shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Clear cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (if authenticated)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID (if guest)",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cart cleared successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cart/items": {
            "post": {
                "description": "Add a product to the shopping cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add item to cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (if authenticated)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID (if guest)",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "description": "Add Item Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AddItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item added successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cart/items/{product_id}": {
            "put": {
                "description": "Update the quantity of an item in the cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Update item quantity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (if authenticated)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID (if guest)",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "description": "Update Item Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item updated successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove an item from the shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Remove item from cart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (if authenticated)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID (if guest)",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item removed successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "Get list of orders for a user or session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "List orders",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Orders retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new order from the shopping cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Create order from cart",
                "parameters": [
                    {
                        "description": "Order creation request",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order created successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orders/number/{order_number}": {
            "get": {
                "description": "Get order details by order number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get order by order number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Number",
                        "name": "order_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "description": "Get order details by order ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get order by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Cart": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "Map of product_id -\u003e CartItem",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.CartItem"
                    }
                },
                "session_id": {
                    "description": "Deprecated: No longer used, kept for backward compatibility",
                    "type": "string"
                },
                "total": {
                    "description": "Total price of all items",
                    "type": "number"
                },
                "updated_at": {
                    "description": "Unix timestamp",
                    "type": "integer"
                },
                "user_id": {
                    "description": "User ID (required - authentication required)",
                    "type": "string"
                }
            }
        },
        "domain.CartItem": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "domain.Order": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "discount": {
                    "description": "GIỮ LẠI",
                    "type": "number"
                },
                "earning_amount": {
                    "description": "THÊM MỚI - Shop thực nhận",
                    "type": "number"
                },
                "final_amount": {
                    "description": "THÊM MỚI - Khách thực trả",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "description": "Order items",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.OrderItem"
                    }
                },
                "merchandise_subtotal": {
                    "description": "Financial breakdown (theo db-diagram.db)",
                    "type": "number"
                },
                "order_number": {
                    "description": "Order identification",
                    "type": "string"
                },
                "ordered_at": {
                    "description": "THÊM MỚI",
                    "type": "string"
                },
                "payment_method": {
                    "description": "Payment \u0026 timestamps",
                    "type": "string"
                },
                "platform_fee": {
                    "description": "THÊM MỚI - Phí sàn",
                    "type": "number"
                },
                "session_id": {
                    "description": "GIỮ LẠI deprecated",
                    "type": "string"
                },
                "shipping_address": {
                    "type": "string"
                },
                "shipping_address_id": {
                    "description": "THÊM MỚI - Reference address table",
                    "type": "integer"
                },
                "shipping_city": {
                    "type": "string"
                },
                "shipping_country": {
                    "type": "string"
                },
                "shipping_discount": {
                    "description": "THÊM MỚI - Mã freeship",
                    "type": "number"
                },
                "shipping_fee": {
                    "description": "Phí vận chuyển",
                    "type": "number"
                },
                "shipping_name": {
                    "description": "Shipping information (GIỮ LẠI)",
                    "type": "string"
                },
                "shipping_phone": {
                    "type": "string"
                },
                "shipping_postal_code": {
                    "type": "string"
                },
                "shipping_province": {
                    "type": "string"
                },
                "shop_id": {
                    "description": "THÊM MỚI - Order từ shop (theo db-diagram.db)",
                    "type": "integer"
                },
                "status": {
                    "description": "Status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.OrderStatus"
                        }
                    ]
                },
                "subtotal": {
                    "description": "GIỮ LẠI (sẽ sync với MerchandiseSubtotal)",
                    "type": "number"
                },
                "tax": {
                    "description": "GIỮ LẠI (không có trong diagram)",
                    "type": "number"
                },
                "total_amount": {
                    "description": "GIỮ LẠI để backward compatibility",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "ĐỔI thành NOT NULL (bỏ guest orders)",
                    "type": "integer"
                },
                "voucher_discount": {
                    "description": "THÊM MỚI - Mã giảm giá",
                    "type": "number"
                }
            }
        },
        "domain.OrderItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "price": {
                    "description": "GIỮ LẠI backward compatibility (sync với PriceAtPurchase)",
                    "type": "number"
                },
                "price_at_purchase": {
                    "description": "THÊM MỚI - Đúng tên theo diagram",
                    "type": "number"
                },
                "product_id": {
                    "description": "GIỮ LẠI backward compatibility",
                    "type": "integer"
                },
                "product_image": {
                    "description": "GIỮ LẠI",
                    "type": "string"
                },
                "product_item_id": {
                    "description": "THÊM MỚI - Reference product_item (SKU)",
                    "type": "integer"
                },
                "product_name": {
                    "description": "GIỮ LẠI",
                    "type": "string"
                },
                "product_sku": {
                    "description": "GIỮ LẠI",
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "subtotal": {
                    "description": "GIỮ LẠI",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.OrderStatus": {
            "type": "string",
            "enum": [
                "pending",
                "paid",
                "processing",
                "shipped",
                "delivered",
                "cancelled"
            ],
            "x-enum-comments": {
                "OrderStatusCancelled": "Order has been cancelled",
                "OrderStatusDelivered": "Order has been delivered",
                "OrderStatusPaid": "Payment completed",
                "OrderStatusPending": "Order created, waiting for payment",
                "OrderStatusProcessing": "Order is being processed",
                "OrderStatusShipped": "Order has been shipped"
            },
            "x-enum-descriptions": [
                "Order created, waiting for payment",
                "Payment completed",
                "Order is being processed",
                "Order has been shipped",
                "Order has been delivered",
                "Order has been cancelled"
            ],
            "x-enum-varnames": [
                "OrderStatusPending",
                "OrderStatusPaid",
                "OrderStatusProcessing",
                "OrderStatusShipped",
                "OrderStatusDelivered",
                "OrderStatusCancelled"
            ]
        },
        "handler.AddItemRequest": {
            "type": "object",
            "required": [
                "name",
                "price",
                "product_id",
                "quantity"
            ],
            "properties": {
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number",
                    "minimum": 0
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateItemRequest": {
            "type": "object",
            "required": [
                "quantity"
            ],
            "properties": {
                "quantity": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "service.CreateOrderRequest": {
            "type": "object",
            "required": [
                "shipping_address",
                "shipping_city",
                "shipping_name",
                "shipping_phone"
            ],
            "properties": {
                "discount": {
                    "type": "number"
                },
                "session_id": {
                    "type": "string"
                },
                "shipping_address": {
                    "type": "string"
                },
                "shipping_city": {
                    "type": "string"
                },
                "shipping_country": {
                    "type": "string"
                },
                "shipping_fee": {
                    "description": "Optional",
                    "type": "number"
                },
                "shipping_name": {
                    "description": "Shipping information",
                    "type": "string"
                },
                "shipping_phone": {
                    "type": "string"
                },
                "shipping_postal_code": {
                    "type": "string"
                },
                "shipping_province": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Order Service API",
	Description:      "Order Service API for e-commerce platform - Cart and Order management endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
